//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksCategoriesBindingDb
    {
        public int ID { get; set; }
        public byte[] Timestamp { get; set; }
        public int BookId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual BookDb Books { get; set; }
        public virtual CategoryDb Categories { get; set; }
    }
}
