//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookDb()
        {
            this.BooksCategoriesBindings = new HashSet<BooksCategoriesBindingDb>();
            this.BooksSetsBindings = new HashSet<BooksSetsBindingDb>();
        }
    
        public int ID { get; set; }
        public byte[] Timestamp { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string Isbn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BooksCategoriesBindingDb> BooksCategoriesBindings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BooksSetsBindingDb> BooksSetsBindings { get; set; }
    }
}
