//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BooksEntities : DbContext
    {
        public BooksEntities()
            : base("name=BooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookDb> Books { get; set; }
        public virtual DbSet<BooksCategoriesBindingDb> BooksCategoriesBindings { get; set; }
        public virtual DbSet<BooksSetsBindingDb> BooksSetsBindings { get; set; }
        public virtual DbSet<CategoryDb> Categories { get; set; }
        public virtual DbSet<SetDb> Sets { get; set; }
    }
}
